# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'virtualthread'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - /opt/mysql_data:/var/lib/mysql